# Site
name: Natalie Hammond Dressage
description: Natalie Hammond Dressage in Wildwood, Missouri. Natalie offers a full line of dressage services including Clinics, Training, Lessons, and Breeding. Natalie&#39;s maiden name was Ottiger.        
meta_description: Natalie Hammond Dressage in Wildwood, Missouri. Natalie offers a full line of dressage services including Clinics, Training, Lessons, and Breeding. Natalie&#39;s maiden name was Ottiger.
logo: /assets/images/Logo-12-2020-black.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'hello@nataliehammond.com'
google_analytics: UA-69145-9
disqus:
sharethis:

# Authors
authors:
  natalie:
    name: Natalie
    display_name: Natalie Hammond Dressage
    image: /assets/images/natalie.jpg
    email: hello@nataliehammond.com
    web: nataliehammond.com
    twitter: natdressage
    description: Hi, I am Natalie Hammond.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: natdressage
  card: summary

facebook:
  app_id:
  publisher: nataliehammond.com
  admins:

social:
name: Natalie Hammond
links:
    - https://twitter.com/natdressage
    - https://www.facebook.com/nhdressage

