[build]
  publish = "dist"

[redirects]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=31536000"

[build]
  command = "npm run build"

[context.production]
  command = "npm run build"

[slug]
  trailing_slash = "ignore"  # Options: "always", "never", "ignore"
